# Monitoring Terragrunt config
# Uses kubeconfig generated by the AKS module (terraform apply in tf/)

locals {
  kubeconfig_path = "${get_parent_terragrunt_dir()}/../../../../modules/aks/kubeconfig_aks-observability"
}
generate "k8s_provider" {
  path      = "k8s-provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "kubernetes" {
      config_path = "${local.kubeconfig_path}"
    }

    provider "helm" {
      kubernetes = {
        config_path = "${local.kubeconfig_path}"
      }
    }
  EOF
}

remote_state {
  backend = "local"
  config = {
    path = "${get_parent_terragrunt_dir()}/terragrunt-state/${path_relative_to_include()}/terraform.tfstate"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

