global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'email-notifications'
receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'edsoncarlos.ec40@gmail.com'
    from: 'edsoncarlos.ec40@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'edsoncarlos.ec40@gmail.com'
    auth_password: "<SUA_SENHA_DE_APP_GMAIL>"
    require_tls: true
    send_resolved: true
- name: 'default-receiver'
