# OpenTelemetry Operator Helm Chart Values
replicaCount: ${otel_operator_replica_count}

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.112.0
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

kubeRBACProxy:
  enabled: true

