# OpenTelemetry Collector Helm Chart Values
replicaCount: ${otel_collector_replica_count}

mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.112.0

config:
  exporters:
    otlp:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
      resource_to_telemetry_conversion:
        enabled: true

  processors:
    batch:
      timeout: 5s
      send_batch_size: 1024

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

