# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform-state"
    key                  = "environments/dev/terraform.tfstate"
    resource_group_name  = "terraform-states"
    storage_account_name = "tfstateqyppc0vt"
  }
}
